openapi: "3.0.0"
info:
  title: Sample geocoder
  description: Encode coords to word.
  version: 0.0.1

servers:
  - url: http://localhost:3333/
    description: Localhost

paths:
  /encode:
    post:
      description: Encode latitude and longitude in to word and return word. if there is an address, it will save the address
      parameters:
        - name: latitude
          in: query
          description: Latitude in coordinates
          required: true
          schema:
            type: string
        - name: longitude
          in: query
          description: Longitude in coordinates
          required: true
          schema:
            type: string
        - name: address
          in: query
          description: Address at this point. If address not empty, save it
          required: false
          schema:
            type: string

      responses:
        '200':    # status code
          description: JSON DTO
          content:
            application/json:
              schema:
                type: object
                properties:
                  word:
                    type: string
        '400':
          description: Invalid latitude or longitude
        '500':
          description: Server error
    get:
      description: "note: recommended to use post"
      parameters:
        - name: latitude
          in: query
          description: Latitude in coordinates
          required: true
          schema:
            type: string
        - name: longitude
          in: query
          description: Longitude in coordinates
          required: true
          schema:
            type: string

      responses:
        '200':    # status code
          description: JSON DTO
          content:
            application/json:
              schema:
                type: object
                properties:
                  word:
                    type: string
        '400':
          description: Invalid latitude or longitude
        '500':
          description: Server error
  /decode:
    get:
      description: "Return latitude, longitude and address, if exists"
      parameters:
        - name: word
          in: query
          description: encoded coordinates
          required: true
          schema:
            type: string

      responses:
        '200':    # status code
          description: JSON DTO
          content:
            application/json:
              schema:
                type: object
                properties:
                  latitude:
                    type: string
                  longitude:
                    type: string
                  address:
                    type: string
        '400':
          description: Invalid word
        '500':
          description: Server error
